name: MagRabbit
options:
  bundleIdPrefix: com.amasaki
  deploymentTarget:
    iOS: "15.0"

targets:
  MagRabbit:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - Sources/MagRabbit
      - path: Sources/MagRabbit/Data
        createIntermediateGroups: true
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: MagRabbit
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UIMainStoryboardFile: ""
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
